version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
    platform: linux/amd64

  order-service:
    depends_on:
      - polar-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order


  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
    platform: linux/amd64

  polar-postgres:
    image: "postgres:14.10"
    container_name: "polar-postgres"
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: # 초기화 스크립트를 컨테이너에 볼륨으로 마운트 한다
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"

  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  polar-keycloak:
    image: "quay.io/keycloak/keycloak:19.0"
    container_name: "polar-keycloak"
    command:
      - start-dev --import-realm # 애플리케이션 시작 시 제공된 설정을 임포트
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
